name: teste-deploy-mongodb

services:
  mongodb:
    image: mongo:8.0.32-noble
    container_name: teste-deploy-mongodb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.4.11-alpine
    container_name: teste-deploy-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
    name: mongodb_data
  redis_data:
    name: redis_data
